sudo: required

services:
  - docker

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker build -t dpca/koffee-kustodian .;
    docker push dpca/koffee-kustodian;
    fi
